name: Java Test Generation 
 
on: [push] 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v2 
 
    - name: Use Java 
      uses: actions/setup-java@v2 
      with: 
        java-version: 14 
        distribution: adopt
    - name: Compile Somma.java 
      run: javac Somma/src/Somma.java 
    - name: Generate Randoop tests 
      run: java -cp Somma/out/production/Somma:randoop-all-4.3.2.jar randoop.main.Main gentests --testclass=Somma --output-limit=100
